<?php
/** @var History $block */
/** @var Escaper $escaper */

use DeveloperHub\CancelOrder\Block\Index;
use DeveloperHub\CancelOrder\Helper\Data;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\History;

$helper = $this->helper(Data::class);
$configFieldEnable = $helper->getConfigFieldEnable();
$configFieldNotice = $helper->getConfigFieldNotice();
$configFieldButton = $helper->getConfigFieldButton();
$customBlock = $block->getLayout()->createBlock(Index::class);
$collection = $customBlock->getCollection();
if (isset($collection)) {
    foreach ($collection as $item) {
        $data[] =[
            'status' =>$item['status'],
            'id' => $item['id'],
            'item_status' => $item['item_status']
        ];
        $collectionData[] = $item['id'];
    }
}
?>

<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $escaper->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $escaper->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <?php if ($configFieldEnable) : ?>
                <th scope="col" class="btn btn-primary"><?= $escaper->escapeHtml(__('Cancel Order')) ?></th>
                <?php endif ?>
                <th scope="col" class="col total"><?= $escaper->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col status"><?= $escaper->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"><?= $escaper->escapeHtml(__('Action ')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <tr data-row-id="<?php echo $_order->getRealOrderId(); ?>">
                    <td data-th="<?= $escaper->escapeHtml(__('Order #')) ?>" class="col id"><?= $escaper->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <?php if ($configFieldEnable) : ?>
                    <td>
                        <?php if (isset($collection)) :?>
                            <?php if (in_array($_order->getRealOrderId(), $collectionData)) : ?>
                                <?php foreach ($data as $item) :
                                    if (($_order->getRealOrderId() == $item['id'])) :
                                        if ($item['status'] == 2) :?>
                                            <p style="color: red">your request has been cancelled </p>
                                        <?php endif; ?>
                                        <?php if ($item['status'] == 1 && $_order->getStatus() == 'canceled') :?>
                                            <p style="color: green">your order has been canceled </p>
                                        <?php endif; ?>
                                        <?php if ($item['status'] == 1 && $_order->getStatus() != 'canceled') :?>
                                            <p style="color: green">your request has been send </p>
                                        <?php endif; ?>
                                        <?php if ($item['item_status'] == 1): ?>
                                            <?php $order[] = $item['id'];?>
                                            <?php $orderArray[] = $item['id'];?>
                                        <?php endif;?>
                                        <?php if ($item['item_status'] == 2): ?>
                                            <?php $array[] = $item['id'];?>
                                            <?php $order[] = $item['id'];?>
                                        <?php endif;?>
                                        <?php if ($item['item_status'] == 3):?>
                                            <?php $cancel[] = $item['id']?>
                                            <?php $order[] = $item['id'];?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                <?php if (isset($order)):?>
                                    <?php if (count($order) == $_order->getTotalItemCount()):?>
                                        <?php echo '' ?>
                                        <?php unset($order); ?>
                                    <?php else:?>
                                        <button id="order-cancellation" class= 'btn btn-secondary order-cancellation'
                                                data-order-id="<?php echo $_order->getRealOrderId(); ?>"
                                                data-mage-init='{"example-modal": {"target": "#modal-content"}}'>
                                            <?php echo $configFieldButton  ?>
                                        </button>
                                    <?php endif; ?>
                                <?php endif;?>
                                <?php if (isset($orderArray)):?>
                                    <?php if (count($orderArray) == $_order->getTotalItemCount()):?>
                                        <p style="color: green">your request has been send </p>
                                        <?php unset($orderArray); ?>
                                    <?php else:?>
                                        <?php unset($orderArray); ?>
                                    <?php endif; ?>
                                <?php endif;?>
                                <?php if (isset($array)):?>
                                    <?php if (count($array) == $_order->getTotalItemCount()):?>
                                        <p style="color: red">your request has been cancelled </p>
                                        <?php unset($array); ?>
                                    <?php else:?>
                                        <?php unset($array); ?>
                                    <?php endif; ?>
                                <?php endif;?>
                                <?php if (isset($cancel)):?>
                                    <?php if (count($cancel) == $_order->getTotalItemCount()):?>
                                        <p style="color: red">your item has been cancelled </p>
                                        <?php unset($cancel); ?>
                                    <?php else:?>
                                        <?php unset($cancel); ?>
                                    <?php endif; ?>
                                <?php endif;?>
                            <?php else: ?>
                                <button id="order-cancellation" class= 'btn btn-secondary order-cancellation'
                                        data-order-id="<?php echo $_order->getRealOrderId(); ?>"
                                        data-mage-init='{"example-modal": {"target": "#modal-content"}}'>
                                    <?php echo $configFieldButton  ?>
                                </button>
                                <div class="show" data-order-id="<?php echo $_order->getRealOrderId(); ?>" ></div>
                            <?php endif; ?>
                        <?php else: ?>
                            <button id="order-cancellation" class= 'btn btn-secondary order-cancellation'
                                    data-order-id="<?php echo $_order->getRealOrderId(); ?>"
                                    data-mage-init='{"example-modal": {"target": "#modal-content"}}'>
                                <?php echo $configFieldButton  ?>
                            </button>
                            <div class="show" data-order-id="<?php echo $_order->getRealOrderId(); ?>" ></div>
                        <?php endif;?>
                    </td>
                    <?php endif; ?>
                    <td data-th="<?= $escaper->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= $escaper->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $escaper->escapeHtml(__('View Order')) ?></span>
                        </a>
                        <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?= /* @noEscape */
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= $escaper->escapeHtml(__('Reorder')) ?></span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
<div id="devhub-cancel-order-modal" style="display: none;">
    <form action="" class="form cancel-order" id="devhub-cancellation-form" method="post"
          data-hasrequired="<?= $escaper->escapeHtml(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="control">
                <p><?php echo __("Do you want to send the order cancellation request?"); ?></p>
            </div>
            <div class="control">
                <input type="hidden" name="order-cancellation-id" value="" class="order-cancellation-id">
                <?php $formKey = $block->getFormKey()?>
                <input type="hidden" name="form_key" value="<?= $escaper->escapeHtml($formKey) ?>" class="form_key">
            </div>
            <div class="field required">
                <label class="label" for="label"><span><?php echo $configFieldNotice; ?></span></label>
                <div class="control">
                    <label>
                        <textarea class="devhub-cancel-order-reason input-text" name="devhub-cancel-order-reason" data-validate="{required:true}"></textarea>
                    </label>
                </div>
            </div>
        </fieldset>
    </form>
</div>









